sonata_admin:
  title: "HMIS-ROSAIRE"
  show_mosaic_button: false
  
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }

  options:
    list_action_button_content: icon

  security:
    handler: sonata.admin.security.handler.role

    role_admin: ROLE_ADMIN
    role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]
